### PR TITLE
Yusuke 1

### PR DESCRIPTION
**Pull request by yusukemh**
I created heatmap on "where" tab, and image will popup when clicking the dots along with other info about each manta sighting.

Major changes to note
-I changed the column name in the clean_data.csv from "Group Size" to "Group_Size"
-Toby, when you add individual pictures, please create sub-folder in image folder so that their path will be "image/mantapics/12.jpg" for example.

### CODE REVIEW

**Comment by tobyem** [comment]
When I open Where.html I'm seeing the basemap but no points or heat map. Should I need to download something or change the directory something is referencing? Sorry I'm not good at troubleshooting this

**Comment by yusukemh** [comment]
That's odd... If you use Chrome, can you go view->develop->developer tool, and see if there is any error?

**Comment by tobyem** [comment]
Screen Shot 2020-11-12 at 10 19 53 PM

**Comment by yusukemh** [comment]
Hmm I am not too sure what's happening.
If you have ad-blocker on Chrome, it might be causing it:
https://stackoverflow.com/questions/4390134/failed-to-load-resource-under-chrome

**Pull request merged**
